version: '3.1'
services:
  stats-server:
    build:
       context: ./statistics/stat-service
       dockerfile: Dockerfile
    image: stat_service_image
    container_name: stat_service_container
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats_db_container:5432/explorewithme

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore

  ewm-service:
    build: ./main-service
    image: main_service_image
    container_name: main_service_container
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm_db_container:5432/ewm
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore
      - STAT-SERVICE-SERVER.URL=http://localhost:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db_container
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=explore
      - POSTGRES_PASSWORD=explore